name: Build pipeline
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build artifact"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test Artifact"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"


